export const CATEGORY_KEYS = ['web', 'mobile', 'automation', 'bots']

export const PORTFOLIO_DATA = {
  web: {
    items: [
      {
        id: 'landing',
        icon: '🚀',
        gradient: 'linear-gradient(135deg, #1a1040 0%, #3b0764 50%, #4c0519 100%)',
        tagEn: 'MARKETING',     tagRu: 'МАРКЕТИНГ',
        titleEn: 'Landing Page', titleRu: 'Лендинг',
        descEn: 'High-converting landing pages that turn visitors into customers.',
        descRu: 'Конвертирующие лендинги, превращающие посетителей в клиентов.',
        hasDemo: true,
      },
      {
        id: 'business',
        icon: '🏢',
        gradient: 'linear-gradient(135deg, #0c1445 0%, #1e3a8a 50%, #0e7490 100%)',
        tagEn: 'CORPORATE',         tagRu: 'КОРПОРАТИВНЫЙ',
        titleEn: 'Business Website', titleRu: 'Бизнес-сайт',
        descEn: 'Full corporate sites with navigation, services and contact forms.',
        descRu: 'Полноценные корпоративные сайты с навигацией, услугами и формой.',
        hasDemo: true,
      },
      {
        id: 'ecom',
        icon: '🛒',
        gradient: 'linear-gradient(135deg, #1a2e05 0%, #14532d 50%, #052e16 100%)',
        tagEn: 'E-COMMERCE',   tagRu: 'ИНТЕРНЕТ-МАГАЗИН',
        titleEn: 'Online Store', titleRu: 'Онлайн-магазин',
        descEn: 'Feature-rich stores with cart, products and checkout flow.',
        descRu: 'Функциональные магазины с корзиной, товарами и оформлением заказа.',
        hasDemo: true,
      },
      {
        id: 'crm',
        icon: '📊',
        gradient: 'linear-gradient(135deg, #1c1200 0%, #713f12 50%, #431407 100%)',
        tagEn: 'SAAS / CRM',  tagRu: 'SaaS / CRM',
        titleEn: 'CRM System', titleRu: 'CRM Система',
        descEn: 'Custom business management systems with contacts, pipeline and analytics.',
        descRu: 'Системы управления бизнесом с контактами, воронкой и аналитикой.',
        hasDemo: true,
      },
    ],
  },

  mobile: {
    items: [
      {
        id: 'ios',
        icon: '📱',
        gradient: 'linear-gradient(135deg, #0a1628 0%, #1e3a6e 50%, #0e2456 100%)',
        tagEn: 'iOS',      tagRu: 'iOS',
        titleEn: 'iOS App', titleRu: 'iOS-приложение',
        descEn: 'Native apps for iPhone and iPad with premium UX.',
        descRu: 'Нативные приложения для iPhone и iPad с премиальным UX.',
        hasDemo: false,
      },
      {
        id: 'android',
        icon: '🤖',
        gradient: 'linear-gradient(135deg, #0d2a0d 0%, #166534 50%, #052e16 100%)',
        tagEn: 'ANDROID',      tagRu: 'ANDROID',
        titleEn: 'Android App', titleRu: 'Android-приложение',
        descEn: 'High-performance Android apps with Material Design.',
        descRu: 'Производительные Android-приложения с Material Design.',
        hasDemo: false,
      },
      {
        id: 'cross',
        icon: '⚡',
        gradient: 'linear-gradient(135deg, #1a0a40 0%, #4c1d95 50%, #1e3a8a 100%)',
        tagEn: 'REACT NATIVE', tagRu: 'REACT NATIVE',
        titleEn: 'Cross-Platform', titleRu: 'Кросс-платформа',
        descEn: 'One codebase for iOS & Android — save budget without losing quality.',
        descRu: 'Одно приложение для iOS и Android — экономия бюджета без потери качества.',
        hasDemo: false,
      },
    ],
  },

  automation: {
    items: [
      {
        id: 'crm-int',
        icon: '🔗',
        gradient: 'linear-gradient(135deg, #071428 0%, #0f2d5e 50%, #1e3a8a 100%)',
        tagEn: 'INTEGRATIONS', tagRu: 'ИНТЕГРАЦИИ',
        titleEn: 'CRM Integrations', titleRu: 'CRM-интеграции',
        descEn: 'Connect your tools into one system: Bitrix, AmoCRM, Google Sheets.',
        descRu: 'Связываем ваши инструменты в единую систему: Bitrix, AmoCRM, Google Sheets.',
        hasDemo: false,
      },
      {
        id: 'parsers',
        icon: '🕸️',
        gradient: 'linear-gradient(135deg, #022c22 0%, #065f46 50%, #047857 100%)',
        tagEn: 'PARSING',        tagRu: 'ПАРСИНГ',
        titleEn: 'Data Parsers', titleRu: 'Парсеры данных',
        descEn: 'Scrape data from websites, marketplaces, social networks.',
        descRu: 'Сбор данных с сайтов, маркетплейсов, соцсетей. Автоматический мониторинг.',
        hasDemo: false,
      },
      {
        id: 'workflow',
        icon: '⚙️',
        gradient: 'linear-gradient(135deg, #1c0a00 0%, #7c2d12 50%, #991b1b 100%)',
        tagEn: 'WORKFLOW',             tagRu: 'WORKFLOW',
        titleEn: 'Workflow Automation', titleRu: 'Workflow-автоматизация',
        descEn: 'Automate routine via n8n, Make, Zapier. Hours of work → seconds.',
        descRu: 'Автоматизация рутины через n8n, Make, Zapier. Часы работы → секунды.',
        hasDemo: false,
      },
    ],
  },

  bots: {
    items: [
      {
        id: 'tg-bot',
        icon: '💬',
        gradient: 'linear-gradient(135deg, #012030 0%, #0369a1 50%, #0284c7 100%)',
        tagEn: 'TELEGRAM',      tagRu: 'TELEGRAM',
        titleEn: 'Telegram Bot', titleRu: 'Telegram-бот',
        descEn: 'Business bots: booking, leads, newsletters, customer support.',
        descRu: 'Боты для бизнеса: запись, заявки, рассылки, поддержка клиентов.',
        hasDemo: false,
      },
      {
        id: 'ai-bot',
        icon: '🧠',
        gradient: 'linear-gradient(135deg, #1a0030 0%, #7e22ce 50%, #be185d 100%)',
        tagEn: 'AI',             tagRu: 'AI',
        titleEn: 'AI Consultant', titleRu: 'AI-консультант',
        descEn: 'Smart bots on Claude / GPT for consultations and sales 24/7.',
        descRu: 'Умные боты на базе Claude/GPT для консультаций и продаж 24/7.',
        hasDemo: false,
      },
      {
        id: 'mini-app',
        icon: '🎮',
        gradient: 'linear-gradient(135deg, #0f0a28 0%, #1e1b4b 50%, #4c1d95 100%)',
        tagEn: 'MINI APP', tagRu: 'MINI APP',
        titleEn: 'Mini App', titleRu: 'Mini App',
        descEn: 'Telegram Mini Apps: catalog, payments, personal account inside Telegram.',
        descRu: 'Telegram Mini Apps: каталог, оплата, личный кабинет внутри Telegram.',
        hasDemo: false,
      },
      {
        id: 'booking-bot',
        icon: '📅',
        gradient: 'linear-gradient(135deg, #022c22 0%, #065f46 50%, #0891b2 100%)',
        tagEn: 'BOOKING',      tagRu: 'BOOKING',
        titleEn: 'Booking Bot', titleRu: 'Бот записи',
        descEn: 'Client booking, reminders, calendar sync.',
        descRu: 'Запись клиентов, напоминания, синхронизация с календарём.',
        hasDemo: false,
      },
    ],
  },
}
