import { createContext, useContext, useState } from "react";

export const LangContext = createContext();

export function useLang() {
  return useContext(LangContext);
}

/* ─── Team data (names never change, only labels/roles translate) ─── */
export const TEAM = [
  {
    name:    "Azamat Seitkali",
    emoji:   "👨‍💻",
    roleEn:  "Lead Engineer",
    roleRu:  "Ведущий инженер",
    tagEn:   "≈ Principal Level",
    tagRu:   "≈ Principal уровень",
    expEn:   "8+ years",
    expRu:   "8+ лет",
    skills:  ["System Design", "React", "Node.js", "AWS", "Python", "Microservices"],
    level:   "lead",
  },
  {
    name:    "Damir Usenov",
    emoji:   "👨‍🚀",
    roleEn:  "Senior Full-Stack Engineer",
    roleRu:  "Старший Full-Stack инженер",
    tagEn:   "Senior",
    tagRu:   "Senior",
    expEn:   "6+ years",
    expRu:   "6+ лет",
    skills:  ["React Native", "Flutter", "TypeScript", "GraphQL", "PostgreSQL"],
    level:   "senior",
  },
  {
    name:    "Aizat Bekova",
    emoji:   "👩‍🎨",
    roleEn:  "UI/UX Designer",
    roleRu:  "UI/UX Дизайнер",
    expEn:   "3+ years",
    expRu:   "3+ года",
    skills:  ["Figma", "Adobe XD", "Prototyping", "Branding"],
    level:   "mid",
  },
  {
    name:    "Bekzod Nurmatov",
    emoji:   "🧑‍💻",
    roleEn:  "QA & DevOps Engineer",
    roleRu:  "QA & DevOps инженер",
    expEn:   "3+ years",
    expRu:   "3+ года",
    skills:  ["Testing", "Docker", "CI/CD", "Linux"],
    level:   "mid",
  },
  {
    name:    "Kamila Isanova",
    emoji:   "👩‍💼",
    roleEn:  "Project Manager",
    roleRu:  "Менеджер проектов",
    expEn:   "4+ years",
    expRu:   "4+ года",
    skills:  ["Scrum", "Jira", "Client Relations", "Planning"],
    level:   "mid",
  },
];

export const T = {
  en: {
    navbar: {
      services:  "Services",
      about:     "About",
      contact:   "Contact",
      cta:       "Start a Project",
    },
    hub: {
      eyebrow:  "BUILT TO PERFORM",
      headline: "One studio, three ways to work with us",
      subtitle: "Pick the direction that matches what you need — each one is a focused product with its own team, process and portfolio.",
      cards: [
        {
          key: "bots",
          title: "Bots / AI Automation",
          desc: "AI assistant, light CRM and automations — an AI employee that never sleeps.",
          cta: "Let's find out",
          status: "live",
        },
        {
          key: "web",
          title: "Web Development",
          desc: "Landing pages to full SaaS platforms — any complexity, any design.",
          cta: "See our work",
          status: "live",
        },
        {
          key: "apps",
          title: "Mobile Apps",
          desc: "Native iOS & Android, Flutter & React Native, published and maintained.",
          cta: "Build one now",
          status: "live",
        },
      ],
      soonBadge: "Coming soon",
    },
    apps: {
      eyebrow: "MOBILE APPS",
      headline: "Build your app. See what you'd actually get.",
      subtitle: "Drag features onto the phone and watch it come alive — fill at least half the slots to launch.",
      dragHint: "Drag a feature onto the phone — or tap one, then tap a slot",
      armedHint: "Now tap a slot to place it",
      previewEmpty: "Your app screen builds itself as you go",
      needMore: "more to launch",
      launchBtn: "Launch 🚀",
      resetBtn: "Build another",
      resultEyebrow: "YOU BUILT",
      bridgeLine: "This wasn't just drag-and-drop — this is exactly how we build real apps. With real code.",
      cta: "Start a project",
    },
    showcase: {
      eyebrow: "RECENT WORK",
      close: "Close",
      enterSite: "Enter site",
      comingSoon: "Link coming soon",
      dragHint: "Drag to rotate",
      signature: {
        tag: "OUR OWN SITE",
        title: "Kato Devv",
        desc: "The site you're on right now — WebGL black hole hero, camera driven by scroll.",
      },
    },
    bots: {
      eyebrow:      "BOTS · AI AUTOMATION",
      headlineLead: "Bots and automations",
      headlineHot:  "built around your business.",
      subtitle: "We build Telegram bots, AI assistants and automations that answer customers, qualify leads and run the busywork — so you don't have to.",
      cta:       "Start a project",
      secondaryCta: "How it works",
      hudOnline:  "ONLINE",
      comingSoonBadge: "Kbot — in development, launching soon",
      flowEyebrow: "HOW IT WORKS",
      flowTitle: "From message to done deal",
      flow: [
        { step: "01", title: "Customer writes",       desc: "Telegram, WhatsApp, your site — wherever they already are." },
        { step: "02", title: "AI understands",         desc: "Real conversation, not a decision tree — it answers, qualifies, sells." },
        { step: "03", title: "Lead lands in CRM",      desc: "Every chat becomes a tracked lead automatically — nothing falls through." },
        { step: "04", title: "Automation takes over",  desc: "Sheets, reminders, follow-ups — the busywork runs itself." },
      ],
      offersEyebrow: "PRICING",
      offersTitle: "What we offer",
      offers: [
        { id: "tg-bot",         name: "Telegram Bot",     price: "from $100",       desc: "Menu, replies, one channel — a fast start without AI." },
        { id: "ai-bot",         name: "AI Consultant",    price: "from $600–800",   desc: "AI-powered dialogue on Claude/GPT — answers and sells 24/7.", featured: true },
        { id: "mini-app",       name: "Mini App",         price: "from $400–600",   desc: "Telegram Mini App: catalog, payments, personal cabinet inside Telegram." },
        { id: "booking-bot",    name: "Booking Bot",      price: "from $300–400",   desc: "Client booking, reminders, calendar sync." },
        { id: "automation-pro", name: "Custom Automation", price: "from $1500–2000", desc: "Multi-channel (Telegram / WhatsApp / site), custom workflows, analytics." },
      ],
      modal: {
        title: "Start a project",
        nameLabel: "Name", namePlaceholder: "Your name",
        emailLabel: "Email", emailPlaceholder: "you@email.com",
        ideaLabel: "Idea", ideaPlaceholder: "Tell us a bit about what you need...",
        submit: "Send", sending: "Sending...",
        success: "Thanks! We'll get back to you within 24 hours.",
        error: "Something went wrong — try again or message us on Telegram.",
      },
    },
    hero: {
      available:    "Available for projects",
      cycleWords:   ["Websites", "Mobile Apps", "AI Bots", "CRM Systems"],
      subtitlePre:  "We build",
      subtitlePost: "that drive real results for modern businesses.",
      subtitle:     "We build websites, mobile apps & AI bots that drive real results for modern businesses.",
      stats:        ["Projects", "Clients", "Satisfaction"],
      statsLabels:  ["Projects", "Clients", "Satisfaction"],
      startProject: "Start a Project",
      viewOurWork:  "View Our Work",
      ourServices:  "Our Services",
      scroll:       "scroll",
      stackLabel:   "Stack",
      servicesLabel: "Services",
      rightTags:    ["Telegram Bots", "AI Integration", "Web Apps", "Mobile Apps", "Automation"],
    },
    services: {
      sectionTitle: "Our Services",
      cards: [
        {
          title: "Web Development",
          description: "Modern, fast websites for your business — from landing pages to full web apps.",
          hint: "Click to see live example →",
          modalTitle: "Web Development",
          modalSub: "Example: Business landing page with SEO & custom design",
        },
        {
          title: "Mobile Apps",
          description: "Android & iOS applications with clean UX and smooth performance.",
          hint: "Click to see live example →",
          modalTitle: "Mobile Apps",
          modalSub: "Example: Finance app — iOS/Android UI mockup",
        },
        {
          title: "Automation",
          description: "Business automation and workflow systems that save you hours every day.",
          hint: "Click to see live example →",
          modalTitle: "Business Automation",
          modalSub: "Example: Order processing pipeline dashboard",
        },
        {
          title: "Bots / AI Bots",
          description: "Smart bots for Telegram, WhatsApp and websites — 24/7 customer support.",
          hint: "Click to see live example →",
          modalTitle: "Bots / AI Bots",
          modalSub: "Example: Telegram / website chat assistant",
        },
      ],
      autoStats: [
        { label: "Tasks Automated", value: "2,847", delta: "↑ 12%",    color: "#6366f1" },
        { label: "Hours Saved",     value: "143h",  delta: "↑ 8%",     color: "#0ea5e9" },
        { label: "Success Rate",    value: "99.4%", delta: "stable",    color: "#22c55e" },
      ],
      n8nRunning:      "● Running...",
      n8nCompleted:    "✓ Completed",
      botScript: [
        { sender: "bot",  text: "Hello! 👋 I'm KatoBot — your smart assistant. How can I help?", delay: 600  },
        { sender: "user", text: "I'd like to learn about your services",                          delay: 1400 },
        { sender: "bot",  text: "Of course! We build websites, mobile apps, automation systems and AI bots 🚀", delay: 1600 },
        { sender: "user", text: "Tell me more about websites",                                     delay: 1300 },
        { sender: "bot",  text: "We create modern, fast websites — from landing pages to online stores. Want to leave a request? 😊", delay: 1800 },
      ],
      botName:         "KatoBot Assistant",
      botOnline:       "● Online",
      botBadge:        "AI Powered",
      chatPlaceholder: "Type a message...",
    },
    about: {
      sectionTitle: "About Us",
      subtitle:     "A dedicated team turning bold ideas into world-class digital products.",
      missionTitle: "Our Mission",
      mission:      "We exist to help businesses grow through exceptional software. Every line of code we write is crafted with precision, performance and your end-users in mind.",
      statsRow: [
        { value: "10+",  label: "Projects Completed" },
        { value: "10+",  label: "Happy Clients" },
        { value: "1+",   label: "Years on Market" },
        { value: "100%", label: "Satisfaction Rate" },
      ],
      teamTitle:   "Meet the Team",
      expLabel:    "experience",
      levelLabel:  { lead: "Lead", senior: "Senior", mid: "Mid-level" },
    },
    contact: {
      sectionTitle: "Let's Work Together",
      subtitle:     "Have a project in mind? We'd love to hear about it. Reach out and we'll get back to you within 24 hours.",
      telegramLabel: "Telegram",
      emailLabel:    "Email",
      hoursLabel:    "Working Hours",
      hoursValue:    "Mon – Fri · 9:00 – 18:00 (UTC+6)",
      locationLabel: "Location",
      locationValue: "Bishkek, Kyrgyzstan",
      formTitle:     "Send a Message",
      name:          "Your name",
      email:         "Your email",
      message:       "Tell us about your project",
      send:          "Send Request",
      sent:          "Sent!",
      errorMsg:      "Something went wrong. Please try again.",
      requiredMsg:   "Please fill in all fields.",
    },
    footer: {
      tagline: "Building the future, one line at a time.",
      nav: {
        services:  "Services",
        about:     "About",
        contact:   "Contact",
      },
      rights: "All rights reserved.",
    },
    demos: {
      contact: { tagPill: "get in touch", responseTime: "24h response time" },
      about:   { tagPill: "who we are", teamCount: "5 Qualified Specialists", teamSub: "A tight-knit team with expertise across development, design and project management" },
      web: {
        navLinks: ["About", "Services", "Portfolio", "Contact"],
        navCta: "Get Started",
        badge: "🚀 #1 Rated Agency 2025",
        h1a: "Grow Your", h1b: "Business Online",
        subtitle: "Modern websites that convert visitors into customers — fast, beautiful and SEO-ready.",
        cta: "Start Project →",
        stats: [
          { n: "98%",  l: "Client Satisfaction" },
          { n: "350+", l: "Projects Done" },
          { n: "2×",   l: "Faster Load Time" },
        ],
        features: [
          { icon: "⚡", title: "Fast Loading",  desc: "Under 1s, optimised for all devices." },
          { icon: "🎨", title: "Custom Design", desc: "Unique look tailored to your brand." },
          { icon: "📈", title: "SEO Ready",     desc: "Rank higher on Google from day one." },
          { icon: "🔒", title: "Secure",        desc: "SSL, GDPR-ready, enterprise security." },
        ],
      },
      mobile: {
        tabs: ["🍎 iOS App", "🤖 Android App"],
        financeTitle: "💳 Finance",
        balanceLabel: "Total Balance",
        balanceChange: "↑ +2.4% this month",
        actions: ["📤 Send", "📥 Receive", "📊 Stats", "➕ Top Up"],
        txTitle: "Transactions",
        txItems: [
          { icon: "🛒", name: "Grocery Store", amt: "-$42.50", neg: true  },
          { icon: "💼", name: "Salary",        amt: "+$3,200", neg: false },
          { icon: "☕", name: "Coffee Shop",   amt: "-$5.80",  neg: true  },
        ],
        greeting: "Good Morning 👋",
        deliveryBadge: "🚚 On the way",
        deliveryTitle: "Your order #4821",
        deliveryEta: "ETA: 12 min",
        cats: ["🍕 Pizza", "🍣 Sushi", "🍔 Burger", "🥗 Salad"],
        popularTitle: "Popular Near You",
        orderBtn: "Order",
      },
    },
  },

  ru: {
    navbar: {
      services:  "Услуги",
      about:     "О нас",
      contact:   "Контакты",
      cta:       "Начать проект",
    },
    hub: {
      eyebrow:  "BUILT TO PERFORM",
      headline: "Одна студия — три способа с нами работать",
      subtitle: "Выберите направление под свою задачу — каждое ведётся как отдельный продукт: своя команда, процесс и портфолио.",
      cards: [
        {
          key: "bots",
          title: "Боты / ИИ-автоматизация",
          desc: "ИИ-ассистент, лёгкая CRM и автоматизации — ИИ-сотрудник, который никогда не спит.",
          cta: "Давайте узнаем",
          status: "live",
        },
        {
          key: "web",
          title: "Веб-разработка",
          desc: "От лендинга до сложных SaaS-платформ — любая сложность, любой дизайн.",
          cta: "Смотреть работы",
          status: "live",
        },
        {
          key: "apps",
          title: "Мобильные приложения",
          desc: "Нативные iOS и Android, Flutter и React Native — с публикацией и поддержкой.",
          cta: "Собрать прямо сейчас",
          status: "live",
        },
      ],
      soonBadge: "Скоро",
    },
    apps: {
      eyebrow: "МОБИЛЬНЫЕ ПРИЛОЖЕНИЯ",
      headline: "Собери своё приложение. Посмотри, что реально получится.",
      subtitle: "Перетаскивай фичи на телефон — он оживает на глазах. Заполни хотя бы половину слотов, чтобы запустить.",
      dragHint: "Перетащи фичу на телефон — или тапни по ней, потом по слоту",
      armedHint: "Теперь тапни по слоту, чтобы разместить",
      previewEmpty: "Экран приложения соберётся сам по мере твоих выборов",
      needMore: "ещё, чтобы запустить",
      launchBtn: "Запустить 🚀",
      resetBtn: "Собрать другое",
      resultEyebrow: "ТЫ СОБРАЛ",
      bridgeLine: "Это была не просто игра с drag-n-drop — именно так мы и создаём настоящие приложения. С помощью реального кода.",
      cta: "Начать проект",
    },
    showcase: {
      eyebrow: "НЕДАВНИЕ РАБОТЫ",
      close: "Закрыть",
      enterSite: "Открыть сайт",
      comingSoon: "Ссылка скоро",
      dragHint: "Тяните, чтобы вращать",
      signature: {
        tag: "НАШ СОБСТВЕННЫЙ САЙТ",
        title: "Kato Devv",
        desc: "Сайт, на котором вы сейчас находитесь — WebGL чёрная дыра, камера управляется скроллом.",
      },
    },
    bots: {
      eyebrow:      "БОТЫ · ИИ-АВТОМАТИЗАЦИЯ",
      headlineLead: "Боты и автоматизации",
      headlineHot:  "под ваш бизнес.",
      subtitle: "Делаем Telegram-ботов, AI-ассистентов и автоматизации, которые отвечают клиентам, квалифицируют лиды и берут рутину на себя — пока вы занимаетесь бизнесом.",
      cta:       "Начать проект",
      secondaryCta: "Как это работает",
      hudOnline:  "НА СВЯЗИ",
      comingSoonBadge: "Kbot — в разработке, скоро на рынке",
      flowEyebrow: "КАК ЭТО РАБОТАЕТ",
      flowTitle: "От сообщения до сделки",
      flow: [
        { step: "01", title: "Клиент пишет",              desc: "Telegram, WhatsApp, сайт — там, где ему удобно." },
        { step: "02", title: "ИИ понимает",                desc: "Живой диалог, а не дерево кнопок — отвечает, квалифицирует, продаёт." },
        { step: "03", title: "Лид попадает в CRM",         desc: "Каждый разговор автоматически становится лидом — ничего не теряется." },
        { step: "04", title: "Автоматизация подключается", desc: "Таблицы, напоминания, follow-up — рутина работает сама." },
      ],
      offersEyebrow: "ТАРИФЫ",
      offersTitle: "Что мы предлагаем",
      offers: [
        { id: "tg-bot",         name: "Telegram-бот",       price: "от $100",       desc: "Меню, ответы, один канал — быстрый старт без ИИ." },
        { id: "ai-bot",         name: "AI-консультант",     price: "от $600–800",   desc: "Умный диалог на базе Claude/GPT — отвечает и продаёт 24/7.", featured: true },
        { id: "mini-app",       name: "Mini App",           price: "от $400–600",   desc: "Telegram Mini App: каталог, оплата, личный кабинет внутри Telegram." },
        { id: "booking-bot",    name: "Бот записи",         price: "от $300–400",   desc: "Запись клиентов, напоминания, синхронизация с календарём." },
        { id: "automation-pro", name: "Кастомная автоматизация", price: "от $1500–2000", desc: "Мультиканальность (Telegram / WhatsApp / сайт), кастомные workflow, аналитика." },
      ],
      modal: {
        title: "Начать проект",
        nameLabel: "Имя", namePlaceholder: "Ваше имя",
        emailLabel: "Email", emailPlaceholder: "you@email.com",
        ideaLabel: "Идея", ideaPlaceholder: "Расскажите немного о том, что нужно...",
        submit: "Отправить", sending: "Отправляем...",
        success: "Спасибо! Свяжемся с вами в течение 24 часов.",
        error: "Что-то пошло не так — попробуйте ещё раз или напишите нам в Telegram.",
      },
    },
    hero: {
      available:    "Открыт для проектов",
      cycleWords:   ["Сайты", "Мобильные Apps", "AI Боты", "CRM Системы"],
      subtitlePre:  "Мы создаём",
      subtitlePost: "которые приносят реальные результаты для вашего бизнеса.",
      subtitle:     "Мы создаём сайты, мобильные приложения и AI-боты, которые приносят реальные результаты для вашего бизнеса.",
      stats:        ["Проектов", "Клиентов", "Довольных"],
      statsLabels:  ["Проектов", "Клиентов", "Довольных"],
      startProject: "Начать проект",
      viewOurWork:  "Смотреть работы",
      ourServices:  "Наши услуги",
      scroll:       "вниз",
      stackLabel:   "Стек",
      servicesLabel: "Услуги",
      rightTags:    ["Telegram Боты", "AI Интеграция", "Веб-приложения", "Мобильные приложения", "Автоматизация"],
    },
    services: {
      sectionTitle: "Наши услуги",
      cards: [
        {
          title: "Веб-разработка",
          description: "Современные быстрые сайты для бизнеса — от лендингов до полноценных веб-приложений.",
          hint: "Нажмите для просмотра →",
          modalTitle: "Веб-разработка",
          modalSub: "Пример: бизнес-лендинг с SEO и уникальным дизайном",
        },
        {
          title: "Мобильные приложения",
          description: "Приложения для Android и iOS с чистым UX и плавной производительностью.",
          hint: "Нажмите для просмотра →",
          modalTitle: "Мобильные приложения",
          modalSub: "Пример: финансовое приложение — макет iOS/Android",
        },
        {
          title: "Автоматизация",
          description: "Системы автоматизации бизнеса, которые экономят часы каждый день.",
          hint: "Нажмите для просмотра →",
          modalTitle: "Автоматизация бизнеса",
          modalSub: "Пример: дашборд обработки заказов",
        },
        {
          title: "Боты / AI Боты",
          description: "Умные боты для Telegram, WhatsApp и сайтов — поддержка клиентов 24/7.",
          hint: "Нажмите для просмотра →",
          modalTitle: "Боты / AI Боты",
          modalSub: "Пример: чат-ассистент для Telegram / сайта",
        },
      ],
      autoStats: [
        { label: "Задач автоматизировано", value: "2,847", delta: "↑ 12%",     color: "#6366f1" },
        { label: "Часов сэкономлено",      value: "143h",  delta: "↑ 8%",      color: "#0ea5e9" },
        { label: "Успешных выполнений",    value: "99.4%", delta: "стабильно",  color: "#22c55e" },
      ],
      n8nRunning:      "● Выполняется...",
      n8nCompleted:    "✓ Завершено",
      botScript: [
        { sender: "bot",  text: "Привет! 👋 Я KatoBot — умный ассистент. Чем могу помочь?", delay: 600  },
        { sender: "user", text: "Хочу узнать о ваших услугах",                               delay: 1400 },
        { sender: "bot",  text: "Конечно! Мы разрабатываем сайты, мобильные приложения, системы автоматизации и AI-боты 🚀", delay: 1600 },
        { sender: "user", text: "Расскажи подробнее про сайты",                              delay: 1300 },
        { sender: "bot",  text: "Создаём современные быстрые сайты под ключ — от лендингов до интернет-магазинов. Хотите оставить заявку? 😊", delay: 1800 },
      ],
      botName:         "KatoBot Ассистент",
      botOnline:       "● Онлайн",
      botBadge:        "AI Powered",
      chatPlaceholder: "Написать сообщение...",
    },
    about: {
      sectionTitle: "О нас",
      subtitle:     "Преданная команда, превращающая смелые идеи в цифровые продукты мирового уровня.",
      missionTitle: "Наша миссия",
      mission:      "Мы помогаем бизнесу расти через создание исключительного программного обеспечения. Каждая строчка кода написана с точностью, производительностью и вашими пользователями в уме.",
      statsRow: [
        { value: "10+",  label: "Завершённых проектов" },
        { value: "10+",  label: "Довольных клиентов" },
        { value: "1+",   label: "Год на рынке" },
        { value: "100%", label: "Удовлетворённость" },
      ],
      teamTitle:  "Познакомьтесь с командой",
      expLabel:   "опыта",
      levelLabel: { lead: "Lead", senior: "Senior", mid: "Middle" },
    },
    contact: {
      sectionTitle:  "Давайте работать вместе",
      subtitle:      "Есть идея для проекта? Мы хотим её услышать. Напишите нам — ответим в течение 24 часов.",
      telegramLabel: "Telegram",
      emailLabel:    "Email",
      hoursLabel:    "Рабочие часы",
      hoursValue:    "Пн – Пт · 9:00 – 18:00 (UTC+6)",
      locationLabel: "Местоположение",
      locationValue: "Бишкек, Кыргызстан",
      formTitle:     "Написать нам",
      name:          "Ваше имя",
      email:         "Ваш email",
      message:       "Расскажите о вашем проекте",
      send:          "Отправить заявку",
      sent:          "Отправлено!",
      errorMsg:      "Что-то пошло не так. Попробуйте ещё раз.",
      requiredMsg:   "Заполните, пожалуйста, все поля.",
    },
    footer: {
      tagline: "Строим будущее — строчка за строчкой.",
      nav: {
        services:  "Услуги",
        about:     "О нас",
        contact:   "Контакты",
      },
      rights: "Все права защищены.",
    },
    demos: {
      contact: { tagPill: "связаться с нами", responseTime: "Ответим за 24 часа" },
      about:   { tagPill: "кто мы такие", teamCount: "5 квалифицированных специалиста", teamSub: "Слаженная команда с опытом в разработке, дизайне и управлении проектами" },
      web: {
        navLinks: ["О нас", "Услуги", "Портфолио", "Контакты"],
        navCta: "Начать",
        badge: "🚀 Агентство №1 в 2025",
        h1a: "Развивайте бизнес", h1b: "в интернете",
        subtitle: "Современные сайты, превращающие посетителей в клиентов — быстро, красиво и с SEO.",
        cta: "Начать проект →",
        stats: [
          { n: "98%",  l: "Довольных клиентов" },
          { n: "350+", l: "Проектов" },
          { n: "2×",   l: "Быстрее загрузка" },
        ],
        features: [
          { icon: "⚡", title: "Быстрая загрузка",  desc: "До 1 сек, оптимизировано для всех устройств." },
          { icon: "🎨", title: "Дизайн под заказ",  desc: "Уникальный вид под ваш бренд." },
          { icon: "📈", title: "SEO оптимизация",   desc: "Выше в Google с первого дня." },
          { icon: "🔒", title: "Безопасность",      desc: "SSL, GDPR, корпоративная защита." },
        ],
      },
      mobile: {
        tabs: ["🍎 iOS App", "🤖 Android App"],
        financeTitle: "💳 Финансы",
        balanceLabel: "Общий баланс",
        balanceChange: "↑ +2.4% за месяц",
        actions: ["📤 Отправить", "📥 Получить", "📊 Статистика", "➕ Пополнить"],
        txTitle: "Транзакции",
        txItems: [
          { icon: "🛒", name: "Продукты",  amt: "-$42.50", neg: true  },
          { icon: "💼", name: "Зарплата",  amt: "+$3,200", neg: false },
          { icon: "☕", name: "Кофейня",   amt: "-$5.80",  neg: true  },
        ],
        greeting: "Доброе утро 👋",
        deliveryBadge: "🚚 В пути",
        deliveryTitle: "Ваш заказ #4821",
        deliveryEta: "Ожидание: 12 мин",
        cats: ["🍕 Пицца", "🍣 Суши", "🍔 Бургер", "🥗 Салат"],
        popularTitle: "Популярное рядом",
        orderBtn: "Заказать",
      },
    },
  },
};

export function LangProvider({ children }) {
  const [lang, setLang] = useState("en");
  const t = T[lang];
  return (
    <LangContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LangContext.Provider>
  );
}
