import { createContext, useContext, useState } from "react";

export const LangContext = createContext();

export function useLang() {
  return useContext(LangContext);
}

/* ─── Team data (names never change, only labels/roles translate) ─── */
export const TEAM = [
  {
    name:    "Azamat Seitkali",
    emoji:   "👨‍💻",
    roleEn:  "Lead Engineer",
    roleRu:  "Ведущий инженер",
    tagEn:   "≈ Principal Level",
    tagRu:   "≈ Principal уровень",
    expEn:   "8+ years",
    expRu:   "8+ лет",
    skills:  ["System Design", "React", "Node.js", "AWS", "Python", "Microservices"],
    level:   "lead",
  },
  {
    name:    "Damir Usenov",
    emoji:   "👨‍🚀",
    roleEn:  "Senior Full-Stack Engineer",
    roleRu:  "Старший Full-Stack инженер",
    tagEn:   "Senior",
    tagRu:   "Senior",
    expEn:   "6+ years",
    expRu:   "6+ лет",
    skills:  ["React Native", "Flutter", "TypeScript", "GraphQL", "PostgreSQL"],
    level:   "senior",
  },
  {
    name:    "Aizat Bekova",
    emoji:   "👩‍🎨",
    roleEn:  "UI/UX Designer",
    roleRu:  "UI/UX Дизайнер",
    expEn:   "3+ years",
    expRu:   "3+ года",
    skills:  ["Figma", "Adobe XD", "Prototyping", "Branding"],
    level:   "mid",
  },
  {
    name:    "Bekzod Nurmatov",
    emoji:   "🧑‍💻",
    roleEn:  "QA & DevOps Engineer",
    roleRu:  "QA & DevOps инженер",
    expEn:   "3+ years",
    expRu:   "3+ года",
    skills:  ["Testing", "Docker", "CI/CD", "Linux"],
    level:   "mid",
  },
  {
    name:    "Kamila Isanova",
    emoji:   "👩‍💼",
    roleEn:  "Project Manager",
    roleRu:  "Менеджер проектов",
    expEn:   "4+ years",
    expRu:   "4+ года",
    skills:  ["Scrum", "Jira", "Client Relations", "Planning"],
    level:   "mid",
  },
];

export const T = {
  en: {
    navbar: {
      services:  "Services",
      portfolio: "Portfolio",
      about:     "About",
      contact:   "Contact",
      cta:       "Start a Project",
    },
    hero: {
      available:    "Available for projects",
      cycleWords:   ["Websites", "Mobile Apps", "AI Bots", "CRM Systems"],
      subtitlePre:  "We build",
      subtitlePost: "that drive real results for modern businesses.",
      subtitle:     "We build websites, mobile apps & AI bots that drive real results for modern businesses.",
      stats:        ["Projects", "Clients", "Satisfaction"],
      statsLabels:  ["Projects", "Clients", "Satisfaction"],
      startProject: "Start a Project",
      viewOurWork:  "View Our Work",
      ourServices:  "Our Services",
      scroll:       "scroll",
      stackLabel:   "Stack",
      servicesLabel: "Services",
      rightTags:    ["Telegram Bots", "AI Integration", "Web Apps", "Mobile Apps", "Automation"],
    },
    services: {
      sectionTitle: "Our Services",
      cards: [
        {
          title: "Web Development",
          description: "Modern, fast websites for your business — from landing pages to full web apps.",
          hint: "Click to see live example →",
          modalTitle: "Web Development",
          modalSub: "Example: Business landing page with SEO & custom design",
        },
        {
          title: "Mobile Apps",
          description: "Android & iOS applications with clean UX and smooth performance.",
          hint: "Click to see live example →",
          modalTitle: "Mobile Apps",
          modalSub: "Example: Finance app — iOS/Android UI mockup",
        },
        {
          title: "Automation",
          description: "Business automation and workflow systems that save you hours every day.",
          hint: "Click to see live example →",
          modalTitle: "Business Automation",
          modalSub: "Example: Order processing pipeline dashboard",
        },
        {
          title: "AI Bots",
          description: "Smart bots for Telegram, WhatsApp and websites — 24/7 customer support.",
          hint: "Click to see live example →",
          modalTitle: "AI Bots",
          modalSub: "Example: Telegram / website chat assistant",
        },
      ],
      autoStats: [
        { label: "Tasks Automated", value: "2,847", delta: "↑ 12%",    color: "#6366f1" },
        { label: "Hours Saved",     value: "143h",  delta: "↑ 8%",     color: "#0ea5e9" },
        { label: "Success Rate",    value: "99.4%", delta: "stable",    color: "#22c55e" },
      ],
      n8nRunning:      "● Running...",
      n8nCompleted:    "✓ Completed",
      botScript: [
        { sender: "bot",  text: "Hello! 👋 I'm KatoBot — your smart assistant. How can I help?", delay: 600  },
        { sender: "user", text: "I'd like to learn about your services",                          delay: 1400 },
        { sender: "bot",  text: "Of course! We build websites, mobile apps, automation systems and AI bots 🚀", delay: 1600 },
        { sender: "user", text: "Tell me more about websites",                                     delay: 1300 },
        { sender: "bot",  text: "We create modern, fast websites — from landing pages to online stores. Want to leave a request? 😊", delay: 1800 },
      ],
      botName:         "KatoBot Assistant",
      botOnline:       "● Online",
      botBadge:        "AI Powered",
      chatPlaceholder: "Type a message...",
    },
    portfolio: {
      sectionTitle: "Portfolio",
      viewProject:  "View Project →",
      cards: [
        { tag: "Marketing",   title: "Landing Page",     desc: "High-converting landing pages that turn visitors into customers." },
        { tag: "Corporate",   title: "Business Website", desc: "Full multi-page corporate sites with navigation, services and contact forms." },
        { tag: "E-commerce",  title: "Online Store",     desc: "Feature-rich e-commerce stores with cart, products and checkout flow." },
        { tag: "SaaS / CRM",  title: "CRM System",       desc: "Custom business management systems with contacts, pipeline and analytics." },
      ],
    },
    about: {
      sectionTitle: "About Us",
      subtitle:     "A dedicated team turning bold ideas into world-class digital products.",
      missionTitle: "Our Mission",
      mission:      "We exist to help businesses grow through exceptional software. Every line of code we write is crafted with precision, performance and your end-users in mind.",
      statsRow: [
        { value: "10+",  label: "Projects Completed" },
        { value: "10+",  label: "Happy Clients" },
        { value: "1+",   label: "Years on Market" },
        { value: "100%", label: "Satisfaction Rate" },
      ],
      teamTitle:   "Meet the Team",
      expLabel:    "experience",
      levelLabel:  { lead: "Lead", senior: "Senior", mid: "Mid-level" },
    },
    contact: {
      sectionTitle: "Let's Work Together",
      subtitle:     "Have a project in mind? We'd love to hear about it. Reach out and we'll get back to you within 24 hours.",
      telegramLabel: "Telegram",
      emailLabel:    "Email",
      hoursLabel:    "Working Hours",
      hoursValue:    "Mon – Fri · 9:00 – 18:00 (UTC+6)",
      locationLabel: "Location",
      locationValue: "Bishkek, Kyrgyzstan",
      formTitle:     "Send a Message",
      name:          "Your name",
      email:         "Your email",
      message:       "Tell us about your project",
      send:          "Send Request",
      sent:          "Sent!",
      errorMsg:      "Something went wrong. Please try again.",
    },
    footer: {
      tagline: "Building the future, one line at a time.",
      nav: {
        services:  "Services",
        portfolio: "Portfolio",
        about:     "About",
        contact:   "Contact",
      },
      rights: "All rights reserved.",
    },
    demos: {
      contact: { tagPill: "get in touch", responseTime: "24h response time" },
      about:   { tagPill: "who we are", teamCount: "5 Qualified Specialists", teamSub: "A tight-knit team with expertise across development, design and project management" },
      web: {
        navLinks: ["About", "Services", "Portfolio", "Contact"],
        navCta: "Get Started",
        badge: "🚀 #1 Rated Agency 2025",
        h1a: "Grow Your", h1b: "Business Online",
        subtitle: "Modern websites that convert visitors into customers — fast, beautiful and SEO-ready.",
        cta: "Start Project →",
        stats: [
          { n: "98%",  l: "Client Satisfaction" },
          { n: "350+", l: "Projects Done" },
          { n: "2×",   l: "Faster Load Time" },
        ],
        features: [
          { icon: "⚡", title: "Fast Loading",  desc: "Under 1s, optimised for all devices." },
          { icon: "🎨", title: "Custom Design", desc: "Unique look tailored to your brand." },
          { icon: "📈", title: "SEO Ready",     desc: "Rank higher on Google from day one." },
          { icon: "🔒", title: "Secure",        desc: "SSL, GDPR-ready, enterprise security." },
        ],
      },
      mobile: {
        tabs: ["🍎 iOS App", "🤖 Android App"],
        financeTitle: "💳 Finance",
        balanceLabel: "Total Balance",
        balanceChange: "↑ +2.4% this month",
        actions: ["📤 Send", "📥 Receive", "📊 Stats", "➕ Top Up"],
        txTitle: "Transactions",
        txItems: [
          { icon: "🛒", name: "Grocery Store", amt: "-$42.50", neg: true  },
          { icon: "💼", name: "Salary",        amt: "+$3,200", neg: false },
          { icon: "☕", name: "Coffee Shop",   amt: "-$5.80",  neg: true  },
        ],
        greeting: "Good Morning 👋",
        deliveryBadge: "🚚 On the way",
        deliveryTitle: "Your order #4821",
        deliveryEta: "ETA: 12 min",
        cats: ["🍕 Pizza", "🍣 Sushi", "🍔 Burger", "🥗 Salad"],
        popularTitle: "Popular Near You",
        orderBtn: "Order",
      },
      landing: {
        navLinks: ["Features", "Pricing", "Blog", "About"],
        navCta: "Start Free Trial",
        badge: "🏆 #1 Fitness App in 2025",
        h1a: "Train Smarter,", h1b: "Get Stronger",
        subtitle: "Personalised workout plans, real-time coaching and progress tracking — all in one sleek app. Reach your goals 3× faster.",
        ctaPrimary: "Get Started Free →", ctaSecondary: "▶ Watch Demo",
        stats: [
          { n: "500K+", l: "Active Users" }, { n: "4.9★", l: "App Store Rating" },
          { n: "1.2M", l: "Workouts Logged" }, { n: "98%", l: "Satisfaction Rate" },
        ],
        featuresTitle: "Everything You Need",
        featuresSub: "Powerful tools to keep you on track and motivated every day.",
        features: [
          { icon: "🎯", title: "Personalised Plans",  desc: "AI-generated training plans adapted to your goals, fitness level, and schedule." },
          { icon: "📺", title: "Live Classes",        desc: "Join 200+ weekly live classes led by certified coaches — HIIT, yoga, strength and more." },
          { icon: "📊", title: "Progress Tracking",   desc: "Visual charts, body stats and milestone badges to keep you motivated every step." },
          { icon: "🍎", title: "Nutrition Log",       desc: "Track macros and calories with our smart food database of 2M+ items." },
          { icon: "👥", title: "Community",           desc: "Connect with friends, share progress and compete in weekly challenges together." },
          { icon: "⌚", title: "Wearable Sync",       desc: "Connects with Apple Watch, Garmin and Fitbit to auto-sync your activity data." },
        ],
        testiTitle: "What Our Users Say",
        testiSub: "Thousands of people have already transformed their lives with FitPeak.",
        ctaTitle: "Ready to Transform Your Body?",
        ctaText: "Join 500,000+ people already reaching their goals with FitPeak.",
        ctaBtn: "Start Free — No Credit Card",
        footerRights: "© 2025 FitPeak. All rights reserved.",
        footerLinks: ["Privacy", "Terms", "Support"],
      },
      business: {
        tabs: ["Home", "Services", "About", "Contact"],
        navCta: "Free Consultation",
        homeH1a: "We Help Businesses", homeH1b: "Scale Smarter",
        homeSubtitle: "Strategy, technology and growth consulting for forward-thinking companies ready to reach the next level.",
        homeCta: "Get Started →",
        stats: [
          { n: "350+", l: "Projects Delivered" }, { n: "98%", l: "Client Satisfaction" },
          { n: "12+",  l: "Years Experience" },   { n: "40+", l: "Expert Consultants" },
        ],
        whatWeDoTitle: "What We Do",
        whatWeDosub: "End-to-end solutions across strategy, technology and operations.",
        homeServices: [
          { icon: "🚀", title: "Growth Strategy",        desc: "Data-driven roadmaps to accelerate your revenue and market share." },
          { icon: "💻", title: "Digital Transformation", desc: "Modernise your tech stack and automate core processes end-to-end." },
          { icon: "📊", title: "Business Analytics",     desc: "Unlock hidden insights in your data to make smarter decisions faster." },
          { icon: "🤝", title: "M&A Advisory",           desc: "Expert guidance on mergers, acquisitions and strategic partnerships." },
        ],
        srvPageTitle: "Our Services",
        srvPageSub: "Tailored consulting packages to match your business stage and goals.",
        srvList: [
          { icon: "🚀", title: "Growth Strategy",          desc: "Market analysis, competitive positioning and revenue roadmap.", price: "from $4,500/mo" },
          { icon: "💻", title: "Digital Transformation",   desc: "Full audit of your processes and technology, followed by a modernisation plan.", price: "from $8,000/mo" },
          { icon: "📊", title: "Business Analytics & BI",  desc: "Custom dashboards, KPI frameworks and data pipelines.", price: "from $3,200/mo" },
          { icon: "🤝", title: "M&A Advisory",             desc: "Due diligence, valuation modelling and integration planning.", price: "from $12,000" },
          { icon: "🎯", title: "Marketing Optimisation",   desc: "Conversion rate optimisation, funnel analysis and campaign reviews.", price: "from $2,800/mo" },
        ],
        abtTitle: "Built on Trust & Results",
        abtText: "Founded in 2013, Nexus Consulting has grown from a two-person boutique into a full-service firm trusted by over 200 companies across 18 countries.",
        teamTitle: "Meet the Leadership Team",
        ctcTitle: "Get in Touch",
        ctcText: "Whether you're looking for a strategic partner or just want to explore what's possible — we'd love to hear from you.",
        ctcItems: [
          { icon: "📍", text: "123 Business Ave, New York, NY 10001" },
          { icon: "📞", text: "+1 (555) 234-5678" },
          { icon: "📧", text: "hello@nexus-consulting.com" },
          { icon: "🕐", text: "Mon–Fri: 9:00 AM – 6:00 PM EST" },
        ],
        ctcForm: { name: "Your Name", email: "Email Address", company: "Company Name", message: "Tell us about your project...", send: "Send Message →" },
        footerRights: "© 2025 Nexus Consulting",
        footerLinks: ["Privacy Policy", "Terms of Service", "Careers"],
      },
      ecom: {
        navLinks: ["Mac", "iPhone", "iPad", "Accessories"],
        bannerBadge: "🔥 Spring Sale — up to 15% off",
        bannerH1a: "Next-Level Tech", bannerH1b: "Delivered Fast",
        bannerSub: "Shop the latest Apple products with free shipping on orders over $99 and 30-day returns.",
        bannerCta: "Shop Now →",
        catTitle: "Category", priceTitle: "Price Range",
        cats: ["All", "Mac", "iPhone", "iPad", "Audio", "Watch"],
        priceRanges: ["Under $500", "$500–$1,000", "Over $1,000"],
        allProducts: "All Products", items: "items",
        addCart: "+ Cart", added: "✓ Added",
        badges: { Bestseller: "Bestseller", New: "New", Sale: "Sale" },
        cartHeader: "Cart", cartEmpty: "Your cart is empty.\nAdd some products!",
        cartTotal: "Total", checkout: "Checkout →",
      },
      crm: {
        nav: [
          { key: "dashboard", icon: "📊", label: "Dashboard" },
          { key: "contacts",  icon: "👥", label: "Contacts"  },
          { key: "pipeline",  icon: "📋", label: "Pipeline"  },
        ],
        admin: "Admin", dashTitle: "Dashboard",
        stats: [
          { icon: "👥", value: "142",   label: "Total Contacts", delta: "↑ 8 this month"   },
          { icon: "📋", value: "37",    label: "Active Deals",   delta: "↑ 5 this week"    },
          { icon: "💰", value: "$284K", label: "Pipeline Value", delta: "↑ 12% vs last mo" },
          { icon: "✅", value: "68%",   label: "Win Rate",       delta: "↑ 3% vs last mo"  },
        ],
        actTitle: "Recent Activity",
        activities: [
          { text: "Bob Martinez moved to In Progress",   time: "2 min ago"   },
          { text: "New contact added — David Lee",       time: "1 hour ago"  },
          { text: "Carol Smith deal closed — $22,000",   time: "3 hours ago" },
          { text: "Proposal sent to Alice Johnson",      time: "Yesterday"   },
          { text: "Follow-up scheduled with Emma Davis", time: "Yesterday"   },
        ],
        tasksTitle: "My Tasks",
        tasks: [
          { id: 1, text: "Follow up with Bob Martinez",  done: false, priority: "high" },
          { id: 2, text: "Prepare Q2 report",            done: true,  priority: "mid"  },
          { id: 3, text: "Send proposal to TechCorp",    done: false, priority: "high" },
          { id: 4, text: "Update pipeline forecasts",    done: false, priority: "mid"  },
          { id: 5, text: "Review new lead — David Lee",  done: true,  priority: "low"  },
        ],
        contTitle: "Contacts", addContact: "+ Add Contact",
        tableHeaders: ["Name", "Status", "Deal Value", "Last Contact", "Actions"],
        statuses: { active: "Active", lead: "Lead", closed: "Closed", new: "New" },
        viewBtn: "View", editBtn: "Edit",
        pipeTitle: "Sales Pipeline",
        pipeStages: { "New Lead": "New Lead", "In Progress": "In Progress", "Closed Won": "Closed Won" },
        tags: { warm: "warm", cold: "cold", hot: "hot" },
      },
    },
  },

  ru: {
    navbar: {
      services:  "Услуги",
      portfolio: "Портфолио",
      about:     "О нас",
      contact:   "Контакты",
      cta:       "Начать проект",
    },
    hero: {
      available:    "Открыт для проектов",
      cycleWords:   ["Сайты", "Мобильные Apps", "AI Боты", "CRM Системы"],
      subtitlePre:  "Мы создаём",
      subtitlePost: "которые приносят реальные результаты для вашего бизнеса.",
      subtitle:     "Мы создаём сайты, мобильные приложения и AI-боты, которые приносят реальные результаты для вашего бизнеса.",
      stats:        ["Проектов", "Клиентов", "Довольных"],
      statsLabels:  ["Проектов", "Клиентов", "Довольных"],
      startProject: "Начать проект",
      viewOurWork:  "Смотреть работы",
      ourServices:  "Наши услуги",
      scroll:       "вниз",
      stackLabel:   "Стек",
      servicesLabel: "Услуги",
      rightTags:    ["Telegram Боты", "AI Интеграция", "Веб-приложения", "Мобильные приложения", "Автоматизация"],
    },
    services: {
      sectionTitle: "Наши услуги",
      cards: [
        {
          title: "Веб-разработка",
          description: "Современные быстрые сайты для бизнеса — от лендингов до полноценных веб-приложений.",
          hint: "Нажмите для просмотра →",
          modalTitle: "Веб-разработка",
          modalSub: "Пример: бизнес-лендинг с SEO и уникальным дизайном",
        },
        {
          title: "Мобильные приложения",
          description: "Приложения для Android и iOS с чистым UX и плавной производительностью.",
          hint: "Нажмите для просмотра →",
          modalTitle: "Мобильные приложения",
          modalSub: "Пример: финансовое приложение — макет iOS/Android",
        },
        {
          title: "Автоматизация",
          description: "Системы автоматизации бизнеса, которые экономят часы каждый день.",
          hint: "Нажмите для просмотра →",
          modalTitle: "Автоматизация бизнеса",
          modalSub: "Пример: дашборд обработки заказов",
        },
        {
          title: "AI Боты",
          description: "Умные боты для Telegram, WhatsApp и сайтов — поддержка клиентов 24/7.",
          hint: "Нажмите для просмотра →",
          modalTitle: "AI Боты",
          modalSub: "Пример: чат-ассистент для Telegram / сайта",
        },
      ],
      autoStats: [
        { label: "Задач автоматизировано", value: "2,847", delta: "↑ 12%",     color: "#6366f1" },
        { label: "Часов сэкономлено",      value: "143h",  delta: "↑ 8%",      color: "#0ea5e9" },
        { label: "Успешных выполнений",    value: "99.4%", delta: "стабильно",  color: "#22c55e" },
      ],
      n8nRunning:      "● Выполняется...",
      n8nCompleted:    "✓ Завершено",
      botScript: [
        { sender: "bot",  text: "Привет! 👋 Я KatoBot — умный ассистент. Чем могу помочь?", delay: 600  },
        { sender: "user", text: "Хочу узнать о ваших услугах",                               delay: 1400 },
        { sender: "bot",  text: "Конечно! Мы разрабатываем сайты, мобильные приложения, системы автоматизации и AI-боты 🚀", delay: 1600 },
        { sender: "user", text: "Расскажи подробнее про сайты",                              delay: 1300 },
        { sender: "bot",  text: "Создаём современные быстрые сайты под ключ — от лендингов до интернет-магазинов. Хотите оставить заявку? 😊", delay: 1800 },
      ],
      botName:         "KatoBot Ассистент",
      botOnline:       "● Онлайн",
      botBadge:        "AI Powered",
      chatPlaceholder: "Написать сообщение...",
    },
    portfolio: {
      sectionTitle: "Портфолио",
      viewProject:  "Открыть проект →",
      cards: [
        { tag: "Маркетинг",        title: "Лендинг",          desc: "Конвертирующие лендинги, превращающие посетителей в клиентов." },
        { tag: "Корпоративный",    title: "Бизнес-сайт",      desc: "Полноценные корпоративные сайты с навигацией, услугами и формой обратной связи." },
        { tag: "Интернет-магазин", title: "Онлайн-магазин",   desc: "Функциональные магазины с корзиной, товарами и оформлением заказа." },
        { tag: "SaaS / CRM",       title: "CRM Система",      desc: "Системы управления бизнесом с контактами, воронкой и аналитикой." },
      ],
    },
    about: {
      sectionTitle: "О нас",
      subtitle:     "Преданная команда, превращающая смелые идеи в цифровые продукты мирового уровня.",
      missionTitle: "Наша миссия",
      mission:      "Мы помогаем бизнесу расти через создание исключительного программного обеспечения. Каждая строчка кода написана с точностью, производительностью и вашими пользователями в уме.",
      statsRow: [
        { value: "10+",  label: "Завершённых проектов" },
        { value: "10+",  label: "Довольных клиентов" },
        { value: "1+",   label: "Год на рынке" },
        { value: "100%", label: "Удовлетворённость" },
      ],
      teamTitle:  "Познакомьтесь с командой",
      expLabel:   "опыта",
      levelLabel: { lead: "Lead", senior: "Senior", mid: "Middle" },
    },
    contact: {
      sectionTitle:  "Давайте работать вместе",
      subtitle:      "Есть идея для проекта? Мы хотим её услышать. Напишите нам — ответим в течение 24 часов.",
      telegramLabel: "Telegram",
      emailLabel:    "Email",
      hoursLabel:    "Рабочие часы",
      hoursValue:    "Пн – Пт · 9:00 – 18:00 (UTC+6)",
      locationLabel: "Местоположение",
      locationValue: "Бишкек, Кыргызстан",
      formTitle:     "Написать нам",
      name:          "Ваше имя",
      email:         "Ваш email",
      message:       "Расскажите о вашем проекте",
      send:          "Отправить заявку",
      sent:          "Отправлено!",
      errorMsg:      "Что-то пошло не так. Попробуйте ещё раз.",
    },
    footer: {
      tagline: "Строим будущее — строчка за строчкой.",
      nav: {
        services:  "Услуги",
        portfolio: "Портфолио",
        about:     "О нас",
        contact:   "Контакты",
      },
      rights: "Все права защищены.",
    },
    demos: {
      contact: { tagPill: "связаться с нами", responseTime: "Ответим за 24 часа" },
      about:   { tagPill: "кто мы такие", teamCount: "5 квалифицированных специалиста", teamSub: "Слаженная команда с опытом в разработке, дизайне и управлении проектами" },
      web: {
        navLinks: ["О нас", "Услуги", "Портфолио", "Контакты"],
        navCta: "Начать",
        badge: "🚀 Агентство №1 в 2025",
        h1a: "Развивайте бизнес", h1b: "в интернете",
        subtitle: "Современные сайты, превращающие посетителей в клиентов — быстро, красиво и с SEO.",
        cta: "Начать проект →",
        stats: [
          { n: "98%",  l: "Довольных клиентов" },
          { n: "350+", l: "Проектов" },
          { n: "2×",   l: "Быстрее загрузка" },
        ],
        features: [
          { icon: "⚡", title: "Быстрая загрузка",  desc: "До 1 сек, оптимизировано для всех устройств." },
          { icon: "🎨", title: "Дизайн под заказ",  desc: "Уникальный вид под ваш бренд." },
          { icon: "📈", title: "SEO оптимизация",   desc: "Выше в Google с первого дня." },
          { icon: "🔒", title: "Безопасность",      desc: "SSL, GDPR, корпоративная защита." },
        ],
      },
      mobile: {
        tabs: ["🍎 iOS App", "🤖 Android App"],
        financeTitle: "💳 Финансы",
        balanceLabel: "Общий баланс",
        balanceChange: "↑ +2.4% за месяц",
        actions: ["📤 Отправить", "📥 Получить", "📊 Статистика", "➕ Пополнить"],
        txTitle: "Транзакции",
        txItems: [
          { icon: "🛒", name: "Продукты",  amt: "-$42.50", neg: true  },
          { icon: "💼", name: "Зарплата",  amt: "+$3,200", neg: false },
          { icon: "☕", name: "Кофейня",   amt: "-$5.80",  neg: true  },
        ],
        greeting: "Доброе утро 👋",
        deliveryBadge: "🚚 В пути",
        deliveryTitle: "Ваш заказ #4821",
        deliveryEta: "Ожидание: 12 мин",
        cats: ["🍕 Пицца", "🍣 Суши", "🍔 Бургер", "🥗 Салат"],
        popularTitle: "Популярное рядом",
        orderBtn: "Заказать",
      },
      landing: {
        navLinks: ["Функции", "Цены", "Блог", "О нас"],
        navCta: "Попробовать",
        badge: "🏆 Приложение №1 в 2025",
        h1a: "Тренируйся умнее,", h1b: "Становись сильнее",
        subtitle: "Персональные тренировки, онлайн-коучинг и отслеживание прогресса — всё в одном приложении. Достигай целей в 3× быстрее.",
        ctaPrimary: "Начать бесплатно →", ctaSecondary: "▶ Смотреть демо",
        stats: [
          { n: "500K+", l: "Пользователей" }, { n: "4.9★", l: "Рейтинг App Store" },
          { n: "1.2M",  l: "Тренировок" },    { n: "98%",  l: "Довольных" },
        ],
        featuresTitle: "Всё что нужно",
        featuresSub: "Мощные инструменты для мотивации и достижения целей каждый день.",
        features: [
          { icon: "🎯", title: "Персональные планы",    desc: "Тренировки под ваши цели, уровень и расписание — генерирует AI." },
          { icon: "📺", title: "Онлайн-занятия",        desc: "200+ еженедельных занятий с сертифицированными тренерами." },
          { icon: "📊", title: "Отслеживание прогресса",desc: "Графики, статистика и значки достижений." },
          { icon: "🍎", title: "Дневник питания",       desc: "Калории и макросы — база из 2M+ продуктов." },
          { icon: "👥", title: "Сообщество",            desc: "Делись прогрессом и соревнуйся в еженедельных челленджах." },
          { icon: "⌚", title: "Синхронизация",         desc: "Apple Watch, Garmin и Fitbit — синхронизация автоматически." },
        ],
        testiTitle: "Что говорят пользователи",
        testiSub: "Тысячи людей уже изменили свою жизнь с FitPeak.",
        ctaTitle: "Готов изменить своё тело?",
        ctaText: "Присоединяйся к 500 000+ людям, достигающим своих целей с FitPeak.",
        ctaBtn: "Начать бесплатно",
        footerRights: "© 2025 FitPeak. Все права защищены.",
        footerLinks: ["Конфиденциальность", "Условия", "Поддержка"],
      },
      business: {
        tabs: ["Главная", "Услуги", "О нас", "Контакты"],
        navCta: "Бесплатная консультация",
        homeH1a: "Помогаем бизнесу", homeH1b: "расти умнее",
        homeSubtitle: "Стратегия, технологии и консалтинг для компаний, готовых выйти на новый уровень.",
        homeCta: "Начать →",
        stats: [
          { n: "350+", l: "Проектов" }, { n: "98%", l: "Довольных клиентов" },
          { n: "12+",  l: "Лет опыта" }, { n: "40+", l: "Экспертов" },
        ],
        whatWeDoTitle: "Что мы делаем",
        whatWeDosub: "Комплексные решения в области стратегии, технологий и операций.",
        homeServices: [
          { icon: "🚀", title: "Стратегия роста",         desc: "Дорожные карты на основе данных для ускорения выручки." },
          { icon: "💻", title: "Цифровая трансформация",  desc: "Модернизируйте tech-стек и автоматизируйте ключевые процессы." },
          { icon: "📊", title: "Бизнес-аналитика",        desc: "Откройте скрытые инсайты для принятия умных решений." },
          { icon: "🤝", title: "M&A консалтинг",          desc: "Экспертное сопровождение слияний и партнёрств." },
        ],
        srvPageTitle: "Наши услуги",
        srvPageSub: "Пакеты консалтинга под ваш этап развития и цели.",
        srvList: [
          { icon: "🚀", title: "Стратегия роста",          desc: "Анализ рынка, конкурентное позиционирование и дорожная карта.", price: "от $4,500/мес" },
          { icon: "💻", title: "Цифровая трансформация",   desc: "Полный аудит процессов и технологий с планом модернизации.", price: "от $8,000/мес" },
          { icon: "📊", title: "Аналитика и BI",           desc: "Дашборды, KPI-фреймворки и пайплайны данных.", price: "от $3,200/мес" },
          { icon: "🤝", title: "M&A консалтинг",           desc: "Due diligence, оценка стоимости и интеграционное планирование.", price: "от $12,000" },
          { icon: "🎯", title: "Маркетинговая оптимизация",desc: "Оптимизация конверсии, анализ воронки и эффективность кампаний.", price: "от $2,800/мес" },
        ],
        abtTitle: "Доверие и результаты",
        abtText: "Основанная в 2013 году, Nexus Consulting выросла в полносервисную фирму, которой доверяют более 200 компаний в 18 странах.",
        teamTitle: "Руководящая команда",
        ctcTitle: "Свяжитесь с нами",
        ctcText: "Ищете стратегического партнёра или просто хотите узнать о возможностях — мы будем рады.",
        ctcItems: [
          { icon: "📍", text: "123 Business Ave, Нью-Йорк, NY 10001" },
          { icon: "📞", text: "+1 (555) 234-5678" },
          { icon: "📧", text: "hello@nexus-consulting.com" },
          { icon: "🕐", text: "Пн–Пт: 9:00 – 18:00 EST" },
        ],
        ctcForm: { name: "Ваше имя", email: "Email", company: "Название компании", message: "Расскажите о проекте...", send: "Отправить →" },
        footerRights: "© 2025 Nexus Consulting",
        footerLinks: ["Политика конфиденциальности", "Условия", "Карьера"],
      },
      ecom: {
        navLinks: ["Mac", "iPhone", "iPad", "Аксессуары"],
        bannerBadge: "🔥 Весенняя распродажа — до 15% скидки",
        bannerH1a: "Технологии нового", bannerH1b: "уровня",
        bannerSub: "Купите последние продукты Apple с бесплатной доставкой от $99 и возвратом в 30 дней.",
        bannerCta: "Купить →",
        catTitle: "Категория", priceTitle: "Цена",
        cats: ["Все", "Mac", "iPhone", "iPad", "Аудио", "Часы"],
        priceRanges: ["До $500", "$500–$1,000", "Свыше $1,000"],
        allProducts: "Все товары", items: "товаров",
        addCart: "+ В корзину", added: "✓ Добавлен",
        badges: { Bestseller: "Хит", New: "Новинка", Sale: "Скидка" },
        cartHeader: "Корзина", cartEmpty: "Корзина пуста.\nДобавьте товары!",
        cartTotal: "Итого", checkout: "Оформить →",
      },
      crm: {
        nav: [
          { key: "dashboard", icon: "📊", label: "Дашборд"  },
          { key: "contacts",  icon: "👥", label: "Контакты" },
          { key: "pipeline",  icon: "📋", label: "Воронка"  },
        ],
        admin: "Администратор", dashTitle: "Дашборд",
        stats: [
          { icon: "👥", value: "142",   label: "Контактов",       delta: "↑ 8 за месяц"      },
          { icon: "📋", value: "37",    label: "Активных сделок", delta: "↑ 5 за неделю"     },
          { icon: "💰", value: "$284K", label: "Воронка",         delta: "↑ 12% vs прош.мес" },
          { icon: "✅", value: "68%",   label: "Конверсия",       delta: "↑ 3% vs прош.мес"  },
        ],
        actTitle: "Последние события",
        activities: [
          { text: "Bob Martinez переведён в «В работе»",   time: "2 мин назад"  },
          { text: "Добавлен контакт — David Lee",          time: "1 час назад"  },
          { text: "Сделка Carol Smith закрыта — $22,000",  time: "3 часа назад" },
          { text: "Предложение отправлено Alice Johnson",  time: "Вчера"        },
          { text: "Запланирован follow-up с Emma Davis",   time: "Вчера"        },
        ],
        tasksTitle: "Мои задачи",
        tasks: [
          { id: 1, text: "Связаться с Bob Martinez",       done: false, priority: "high" },
          { id: 2, text: "Подготовить отчёт Q2",           done: true,  priority: "mid"  },
          { id: 3, text: "Отправить предложение TechCorp", done: false, priority: "high" },
          { id: 4, text: "Обновить прогнозы воронки",      done: false, priority: "mid"  },
          { id: 5, text: "Проверить лид — David Lee",      done: true,  priority: "low"  },
        ],
        contTitle: "Контакты", addContact: "+ Добавить",
        tableHeaders: ["Имя", "Статус", "Сумма сделки", "Последний контакт", "Действия"],
        statuses: { active: "Активный", lead: "Лид", closed: "Закрыт", new: "Новый" },
        viewBtn: "Смотреть", editBtn: "Изменить",
        pipeTitle: "Воронка продаж",
        pipeStages: { "New Lead": "Новый лид", "In Progress": "В работе", "Closed Won": "Закрыт" },
        tags: { warm: "тёплый", cold: "холодный", hot: "горячий" },
      },
    },
  },
};

export function LangProvider({ children }) {
  const [lang, setLang] = useState("en");
  const t = T[lang];
  return (
    <LangContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LangContext.Provider>
  );
}
